# 9:Promise
想要彻底的了解 `Promise` 必须了解 Promise出现的原因以及 `Promise` 所解决的问题
## 回调地狱
在异步编程中, 往往都要使用很多的异步回调,比如说我们想要发送网路请求,具体可一封装以下几种函数<br>
`makeRequest`函数, 用于构建封装 request请求对象,包含请求的具体信息
```js
function makeRequest(request_url) {
    let request = {
        method: 'Get',
        url: request_url,
        headers: '',
        body: '',
        credentials: false,
        sync: true,
        responseType: 'text',
        referrer: ''
    }
    return request
}
```
`XFetch` 函数, 封装了具体的请求过程以及请求成功和失败的处理逻辑
```js
function XFetch(request, resolve, reject) {
    let xhr = new XMLHttpRequest()
    xhr.ontimeout = function (e) { reject(e) }
    xhr.onerror = function (e) { reject(e) }
    xhr.onreadystatechange = function () {
        if (this.readyState === 4){
            if (this.status === 200) {
                resolve(xhr.response)
            } else {
                let err = {
                    code : this.status,
                    response: this.response
                }
                reject(err)
            }
        }
    }
    xhr.open(request.method, request.url, request.sync);
    xhr.timeout = request.timeout;
    xhr.responseType = request.responseType;
    //补充其他请求信息
    //...
    xhr.send();
}
```
下面就可以基于上面封装的函数进行相应的网络请求
```js
XFetch(makeRequest('https://dog.ceo/api/breeds/image/random'),
    function resolve(data) {
        console.log(data)
    }, function reject(e) {
        console.log(e)
})
```
简单的请求看起来并没有什么问题,但是如果**每次请求都基于上次请求成功后再执行请求**那么代结构就会如下
```js
XFetch(makeRequest('https://dog.ceo/api/breeds/image/random'),
    function resolve(response) {
        console.log(response)
        XFetch(makeRequest('https://dog.ceo/api/breeds/image/random'),
            function resolve(response) {
                console.log(response)
                XFetch(makeRequest('https://dog.ceo/api/breeds/image/random')
                    function resolve(response) {
                        console.log(response)
                    }, function reject(e) {
                        console.log(e)
                    })
            }, function reject(e) {
                console.log(e)
            })
    }, function reject(e) {
        console.log(e)
})
```
这种多层嵌套的回调函数就叫做 `回调地狱(callbackhell)` 为了解决回调地狱这种现象,就引入了Promise这个概念
## Promise
Promise的出现就是为了解决回调地狱的问题,以下代码解决上述的回调地狱
``` js
let executor = (resolve, reject) => {
    XFetch(makeRequest('https://dog.ceo/api/breeds/image/random'), function(result){
        resolve(result)
    }, function(resion) {
        reject(resion)
    })
}
let p0 = new Promise(executor)
let p1 = p0.then(result => {
    console.log(result)
    return new Promise(executor)
}, resion => {
    console.log(resion)
})
let p2 = p1.then(result => {
    console.log(result);
    return new Promise(executor)
}, resion => {
    console.log(resion);
})
p2.then(result => {
    console.log(result);
}, resion => {
    console.log(resion);
})
```
你可以自己尝试执行上述的代码,会发现上述代码也会基于上次的返回成功条件下依次执行
## Promise 基本使用
Promise 本身有三个状态值<br>
- pending 初始状态(new Promise()之后)
- fulfilled 代表操作成功 (resolve)
- rejected 代表当前操作失败
<br>
Promise 本身有一个 value 值,用来记录操作成功或者失败的结果

```js
let p1 = new Promise((resolve, reject) => {
    // 一般会在异步操作结束后,执行 resolve 或者 reject函数,都可以修改 Promise 的[PromiseStatus] 和[PromiseResult]
    // 一旦执行了 resolve 或者 reject 下一个 resolve 和 reject就无效了
    setTimeout(() => {
        reject('no')
    }, 100)
})
```
执行上述代码可以在控制台打印出 `p1` 的 `PromiseState` 变成了 `rejected`,  `PromiseResult` 变成了 `no`<br><br>

Promise 执行过程<br>
1. 创建 Promise实例对象,执行 executor 函数中的方法，遇到异步任务将异步任务放到循环队列中
2. 调用 实例对象的 then 方法，将两个函数储存起来(此时两个函数还没有执行),当 executor 中的异步函数执行结束后,基于resolve/reject 控制 Promise状态,从而决定执行 then 存储中的哪一个函数

```js
let p1 = new Promise((resolve, reject) => {
    setTimeout(() => {
        let ran = Math.random()
        console.log(ran);
        if (ran < 0.5) {
            reject('失败了')
        } else {
            resolve('成功了')
        }
    }, 100)
})
p1.then((result) => {
    console.log('resolve: ' + result)
}, (resion)=> {
    console.log('reject: ' + resion)
})
```
每次 then 方法执行完都会返回一个新的 Promise 实例， 新的 Promise 实例 `PromisStates:pending`,`PromiseResult:undefined`<br><br>
再看下面代码
```js
let p1 = new Promise((resolve, reject) => {
    reject(500)
})
// p2的状态取决于 p1.then 中的两个函数中其中一个的执行结果, 无论哪个方法抛出异常都会把 p1的状态改为失败,抛出异常的信息作为失败的原因(抛出异常后面的代码不会执行)
// 如果 p1.then 中返回了一个新的 Promise 实例, 返回这个实例的成功或者失败,决定了 p2的成功或者失败
// 这里的情况是剩下的情况,将 p2 变成成功状态, 将返回的结果传给 p2.then中的成功方法中
p2 = p1.then(resolve => {
    console.log('p1成功了' + resolve);
    return 200
}, reject => {
    console.log('p1失败了' + reject);
    return 500
})
p3 = p2.then(resolve => {
    console.log('p2 成功了' + resolve);
}, reject => {
    console.log('p2 失败了' + reject);
})
```
上述代码中 <br>
1. p1 这个 new Promise 的实例,状态的成功或者失败,取决于executor 函数执行的时候, 执行是 resolve 还是 reject决定的,如果 exectour 函数执行发生异常错误,也会把实例改为失败的,并执行reject
2. p2/p3这种每一次执行 .then 返回的新实例的状态, 由 then 中存储的方法执行的结果来决定最后的状态(上一个then 中某一个方法的执行结果,决定下一个 then 中哪个方法被执行)
- 不论是成功的方法执行，还是失败的方法执行（then中的两个方法），凡是抛出了异常都会把实例状态改为失败
- 方法中如果返回了一个新的 Promise 实例, 返回这个实例的结果是成功还是失败,也决定了当前实例是成功还是失败
- 剩下的情况都是让实例变为成功状态(上一个 then 中返回的结果会传递到下一个 then 的方法中)